#!/usr/bin/env ruby

$: << File.expand_path(File.dirname(__FILE__))

require 'render'
require 'search'
require 'problem'
require 'node'

class Hanoi
  def initialize
    @problem = Problem.new(disks = cfg(0, 3) , pegs = cfg(1, 5))
    @search  = Search.new(@problem)
  end

  def play
    if goal = @search.run
      Render.new(@problem, goal).animate
      puts "explored %d nodes" % @search.explored_size
    else
      abort "failed to reach goal state"
    end
  end

  private

    def cfg(index, default)
      (ARGV[index] || default).to_i
    end
end

hanoi = Hanoi.new
hanoi.play

