#!/usr/bin/env ruby

$: << File.expand_path(File.dirname(__FILE__))

require 'render'
require 'search'
require 'problem'
require 'node'

class Hanoi
  def initialize
    @problem = Problem.new(disks = 4, pegs = 3)
    @search = Search.new(@problem)
  end

  def play
    if goal = @search.run
      Render.new(@problem, goal).animate
      puts "problem solved after exploring #{ @search.explored_size } nodes"
    else
      abort "failed to reach goal state"
    end
  end
end

hanoi = Hanoi.new
hanoi.play

